version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/scripts/docker/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
