language: bash
sudo: require
dist: trusty

arch:
  - amd64
  - arm64

script:
  - echo -e "nameserver 8.8.8.8\nnameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf # Fix 'temporary error (try again later)'? https://github.com/gliderlabs/docker-alpine/issues/386 
  # 64-bit
  - if [ "$TRAVIS_ARCH" == "aarch64" ] ; then export ARCHITECTURE=aarch64; else export ARCHITECTURE=x86_64; fi
  - env
  - bash -ex build.sh
  # Also build 32-bit versions in the same go
  - if [ "$TRAVIS_ARCH" == "aarch64" ] ; then export ARCHITECTURE=armhf; else export ARCHITECTURE=x86; fi
  - env
  - bash -ex build.sh
  
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./out/*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
