name: build

on:
  push:
    branches:    
      - 'main'
  pull_request:
  
# This ensures that jobs get canceled when force-pushing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
# The default Debian shell (dash) is faster than bash at running scripts,
# and using bash when it is not needed doesn't make sense.
defaults:
  run:
    shell: sh

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - { qemu_arch: x86,     appimage_arch: x86 }
        - { qemu_arch: x86_64,  appimage_arch: x86_64 }
        - { qemu_arch: armv7,   appimage_arch: armhf }
        - { qemu_arch: aarch64, appimage_arch: aarch64 }

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get git hash
      run: |
           echo -n "https://github.com/${GITHUB_REPOSITORY}/commit/" > src/runtime/version
           git rev-parse --short HEAD  | xargs >> src/runtime/version

    - name: Build
      env:
        ARCHITECTURE: ${{ matrix.appimage_arch }}
      run: ./chroot_build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./out/*
        
    - name: Upload to GitHub Releases
      if: github.event_name != 'pull_request' && github.ref_name == 'main'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          ./out/*
